sul-dlss/folio-graphql

schema.graphql, src/index.ts, src/locations-api.ts, src/schema.ts, src/type-api.ts
=> Add location type information to the graph

schema.graphql, src/index.ts, src/schema.ts
=> Use DateTime type in schema instead of Date

schema.graphql, src/feefines-api.ts, src/index.ts, src/schema.ts
Nest FeeFine within existing Charge type
=> Add FeeFine API and type

docker-compose.yml
This allows us to publish the image by doing:
```
docker compose push
```
=> Set the image name

Dockerfile, package.json
Builds haven't been building:
```
#11 [6/6] RUN npm ts-build
#11 0.731 Unknown command: "ts-build"
#11 0.731 
#11 0.731 Did you mean this?
#11 0.731     npm rebuild # Rebuild a package
#11 0.731 
#11 0.732 To see a list of supported npm commands, run:
#11 0.732   npm help
#11 DONE 0.8s
```
=> Add an explicit build step

nodemon.json
We also need to recompile the graphql schema etc when the underlying files change
=> Add some more compilation steps to nodemon

schema.graphql, src/index.ts, src/schema.ts, src/users-api.ts
Part of https://github.com/sul-dlss/sul-requests/issues/1460. FOLIO doesn't apply a status label, as such, so we have to go looking for what's wrong and infer the status from there.
=> Retrieve patron blocks

schema.graphql, src/index.ts, src/schema.ts, src/users-api.ts
Part of https://github.com/sul-dlss/mylibrary/issues/737
=> Expose proxies through the user

codegen.yml, src/context.ts, src/folio/index.ts, src/resolvers-types.ts, src/server.ts
Seems like they thought of everything.
=> Let graphql type the resolver context for us

src/resolvers-types.ts, src/schema.graphql, src/schema.ts
Based on prior discussion, part of deciding which service point will be the default selection for a location is seeing which campus the service point is associated with.
We are storing "isDefaultForCampus" at the service point level in the details object. 
The sample query 
```
query ServicePoints {
servicePoints {
code
description
pickupLocation
details {
isDefaultForCampus
isDefaultPickup
notes
}
}
}
```
returns
```
{
"data": {
"servicePoints": [
{
"code": "Online",
"description": null,
"pickupLocation": false,
"details": null
},
{
"code": "cd1",
"description": null,
"pickupLocation": false,
"details": null
},
{
"code": "CLASSICS",
"description": null,
"pickupLocation": false,
"details": null
},
{
"code": "ARS",
"description": null,
"pickupLocation": true,
"details": null
},
{
"code": …
```
=> Relating campus to service point

src/resolvers-types.ts, src/schema.graphql, src/schema.ts
Part of https://github.com/sul-dlss/sul-requests/issues/1661
=> Add a pagingSchedule attribute for location details

src/resolvers-types.ts, src/schema.graphql, src/schema.ts
I'm not sure we have any immediate need for this key, but I think it makes sense to "register" it here in case we discover a similar need 🤷‍♂️
=> Add discoveryDisplayUrl to LocationDetails

.github/workflows/docker_build.yml
Ref #103
See https://github.com/docker/metadata-action for configuration options
=> Push docker tags on release

Jenkinsfile
=> Only deploy tagged releases to production

Jenkinsfile
latest is now an alias for the latest versioned release
=> Deploy the :main tag to folio-test

__tests__/item-api.test.ts, src/folio/index.ts
Fixes https://github.com/sul-dlss/mylibrary/issues/944
=> Handle item note type enum values

Jenkinsfile
CI keeps reporting failures and it's because of the new builds from DockerHub.
Previously Github directly triggered Jenkins builds on either a tag starting with v, or a push to main.
Now both of these scenarios trigger a Docker Hub image build, which gets forwarded to Jenkins. Jenkins automatically runs tag and branch based builds as well. This was causing multiple attempts to restart the docker container on the server at the same time, leading to failure reports in our Slack channel.
The logic here is a little extra, I don't really love it but -- here's what I had to do.
For main branch pushes, make sure we aren't also running a tag build.
For `v*` tag pushes, make sure we are only running a tag that was applied on the main branch, but don't also run the branch trigger build.
I tested …
=> Prevent conflict between branch and tag builds in Jenkins

src/folio/index.ts
```
notes {
note
itemNoteType {
name
source
}
}
```
Added source to the query, seemed potentially useful? Works!
@dnoneill Feel free to steal from this branch or use the PR.
=> Add resolver for ItemNoteType

src/resolvers-types.ts, src/schema.graphql, src/schema.ts
Fixes https://github.com/sul-dlss/sul-requests/issues/2668
=> Add In_process_non_requestable LocationAvailabilityClass detail.

src/folio/service-points-api.ts, src/server.ts
These are flagged on every pull request
=> Remove unused variables that GH doesn't like
